name: Label Unread Discussion
on:
  discussion_comment:
    types: [created]

jobs:
  label_discussion:
    name: Label Unread Discussion
    if: ${{ github.event.discussion.category.name == 'Ongoing' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
      - name: Get label_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: unifyai
          REPOSITORY: ivy
          LABEL_NAME: 'Unread'
        run: |
          gh api -H "Accept: application/vnd.github.v3+json" /repos/$ORGANIZATION/$REPOSITORY/labels/$LABEL_NAME > label_data.json
          echo 'LABEL_ID='$(jq '.data.id' label_data.json) >> $GITHUB_ENV
      - name: Add label to discussion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCUSSION_ID: ${{ github.event.discussion.node_id }}
        run: |
          gh api graphql -f query='
            mutation (
              $label_id: [ID!]!
              $labelable_id: ID!
            ) {
              set_label: addLabelsToLabelable(input: {
                labelId: $label_id
                labelableId: $labelable_id
              }) {
                labelable {
                  labels
                }
              }
            }' -f label_id=[$LABEL_ID] -f labelable_id=$DISCUSSION_ID --silent
