name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/ivy:/ivy ivydl/ivy:latest python3 -m pytest ivy/ivy_tests/
