name: test-array-api
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Run JAX Tests
        run: |
          docker run --rm --env ARRAY_API_TESTS_MODULE="ivy.functional.backends.jax" -v `pwd`/ivy:/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_array_api

      - name: Run NumPy Tests
        run: |
          docker run --rm --env ARRAY_API_TESTS_MODULE="ivy.functional.backends.numpy" -v `pwd`/ivy:/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_array_api

      - name: Run TensorFlow Tests
        run: |
          docker run --rm --env ARRAY_API_TESTS_MODULE="ivy.functional.backends.tensorflow" -v `pwd`/ivy:/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_array_api

      - name: Run Torch Tests
        run: |
          docker run --rm --env ARRAY_API_TESTS_MODULE="ivy.functional.backends.torch" -v `pwd`/ivy:/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_array_api -k 'not uint16 and not uint32 and not uint64'
